export interface Quote {
    id: number;
    text: { tr: string; en: string };
    author: { tr: string; en: string };
}

export const QUOTES: Quote[] = [
    { id: 1, text: { tr: "Huzurlu bir uyku, ruhun en güzel ilacıdır.", en: "A peaceful sleep is the best medicine for the soul." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 2, text: { tr: "Gece, yıldızların fısıldadığı saatlerdir.", en: "Night is the hour when the stars whisper." }, author: { tr: "Mevlana", en: "Rumi" } },
    { id: 3, text: { tr: "Uykuya dalmak, günün yükünü bırakmaktır.", en: "Falling asleep is letting go of the day's burden." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 4, text: { tr: "Sessizlik, kalbin en derin melodisidir.", en: "Silence is the deepest melody of the heart." }, author: { tr: "Yunus Emre", en: "Yunus Emre" } },
    { id: 5, text: { tr: "Geceyi sevmek, huzuru sevmektir.", en: "To love the night is to love peace." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 6, text: { tr: "Yıldızlar altında uyumak, evrenle bir olmaktır.", en: "Sleeping under the stars is becoming one with the universe." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 7, text: { tr: "Her gece yeni bir başlangıçtır.", en: "Every night is a new beginning." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 8, text: { tr: "Rüyalar, ruhun özgür kaldığı anlardır.", en: "Dreams are the moments when the soul is completely free." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 9, text: { tr: "Huzur, içinde taşıdığın sessizliktir.", en: "Peace is the silence you carry within." }, author: { tr: "Mevlana", en: "Rumi" } },
    { id: 10, text: { tr: "Gece karanlık değildir, dinlenmektir.", en: "Night is not dark, it is a time for rest." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 11, text: { tr: "Uyku, doğanın en yumuşak bakıcısıdır.", en: "Sleep is nature's softest nurse." }, author: { tr: "William Shakespeare", en: "William Shakespeare" } },
    { id: 12, text: { tr: "Sakin bir zihin, huzurlu bir uykunun anahtarıdır.", en: "A calm mind is the key to a peaceful sleep." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 13, text: { tr: "Yağmurun sesi, doğanın ninnisidir.", en: "The sound of rain is nature's lullaby." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 14, text: { tr: "Ateşin sıcaklığı, ruhun tesellisidir.", en: "The warmth of a fire is comfort for the soul." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 15, text: { tr: "Gecenin güzelliği, sessizliğinde gizlidir.", en: "The beauty of the night is hidden in its silence." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 16, text: { tr: "Derin bir nefes al, bugünü bırak.", en: "Take a deep breath and let go of today." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 17, text: { tr: "Sabır ve huzur, en güzel hazinelerdir.", en: "Patience and peace are the greatest treasures." }, author: { tr: "Hz. Ali", en: "Ali ibn Abi Talib" } },
    { id: 18, text: { tr: "Rüzgârın şarkısını dinle, huzuru hisset.", en: "Listen to the song of the wind, feel the peace." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 19, text: { tr: "Her uyku, bir iyileşme yolculuğudur.", en: "Every sleep is a journey of healing." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 20, text: { tr: "Karanlık gecelerin ardından aydınlık sabahlar gelir.", en: "Bright mornings come after dark nights." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 21, text: { tr: "Kendine iyi bak, uyku en güzel hediyedir.", en: "Take care of yourself, sleep is the greatest gift." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 22, text: { tr: "Yıldızlar seninle uyur, güneş seninle uyanır.", en: "The stars sleep with you, the sun wakes up with you." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 23, text: { tr: "Huzurlu bir gece, mutlu bir yarının habercisidir.", en: "A peaceful night is the herald of a happy tomorrow." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 24, text: { tr: "Gözlerini kapat, dünyayı bir süre unut.", en: "Close your eyes and forget the world for a while." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 25, text: { tr: "Dinlenmek de bir sanattır.", en: "Resting is also an art." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 26, text: { tr: "Gece, ruhun kendini bulduğu zamandır.", en: "Night is the time when the soul finds itself." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 27, text: { tr: "Sessizlikte büyük bir güç vardır.", en: "There is great power in silence." }, author: { tr: "Lao Tzu", en: "Lao Tzu" } },
    { id: 28, text: { tr: "Uyku, zihnin yeniden doğuşudur.", en: "Sleep is the rebirth of the mind." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 29, text: { tr: "Her nefes, yeni bir huzur damlasıdır.", en: "Every breath is a new drop of serenity." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 30, text: { tr: "Geceyi kucakla, huzuru yakala.", en: "Embrace the night, catch the peace." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 31, text: { tr: "Ay ışığında bile umut vardır.", en: "There is hope even in the moonlight." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 32, text: { tr: "Yorgun bedene en güzel armağan, derin bir uykudur.", en: "The best gift for a tired body is a deep sleep." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 33, text: { tr: "Sükûnet, en güçlü duadır.", en: "Tranquility is the strongest prayer." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 34, text: { tr: "Rüyalarında kaybol, gerçekliğinde güçlen.", en: "Get lost in your dreams, grow stronger in your reality." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 35, text: { tr: "Gece, düşüncelerin yumuşadığı zamandır.", en: "Night is the time when thoughts soften." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 36, text: { tr: "İyi geceler, güzel rüyalar... Yarın yeni bir gün.", en: "Good night, sweet dreams... Tomorrow is a new day." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 37, text: { tr: "Doğanın sesi, en güzel müziktir.", en: "The sound of nature is the most beautiful music." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 38, text: { tr: "Bir yastığa başını koymak, şükretmek demektir.", en: "To lay your head on a pillow means to be thankful." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 39, text: { tr: "Huzur, aramakla değil, bırakmakla bulunur.", en: "Peace is found not by seeking, but by letting go." }, author: { tr: "Mevlana", en: "Rumi" } },
    { id: 40, text: { tr: "Gece vakti her şey daha derinden hissedilir.", en: "Everything is felt more deeply at night time." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 41, text: { tr: "Uyku, bedenin doğaya olan teşekkürüdür.", en: "Sleep is the body's gratitude to nature." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 42, text: { tr: "Karanlıkta bile ışık taşıyan ruhlar vardır.", en: "There are souls carrying light even in the dark." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 43, text: { tr: "Nefes al... Bırak... Huzur bul.", en: "Breathe in... Let go... Find peace." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 44, text: { tr: "Gecenin sesi, kalbin melodisidir.", en: "The sound of the night is the melody of the heart." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 45, text: { tr: "Her kapanan göz, açılan bir rüya kapısıdır.", en: "Every closed eye is an opened door to dreams." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 46, text: { tr: "Sıcak bir örtü, soğuk bir gecenin en güzel dostu.", en: "A warm blanket is the best friend of a cold night." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 47, text: { tr: "Uyumak, günün en cesur adımıdır.", en: "Sleeping is the bravest step of the day." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 48, text: { tr: "Yıldızlar altında herkes eşittir.", en: "Everyone is equal under the stars." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 49, text: { tr: "Gece, zamanın yavaşladığı andır.", en: "Night is the moment when time slows down." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 50, text: { tr: "İç huzurun olmadan dış huzur bulamazsın.", en: "You cannot find outer peace without inner peace." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 51, text: { tr: "Rüyalar, gerçeğin yumuşak halidir.", en: "Dreams are the soft version of reality." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 52, text: { tr: "Bir gün biter, başka bir gün başlar. Arada uyku vardır.", en: "One day ends, another begins. In between, there is sleep." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 53, text: { tr: "Gecenin en karanlık anı, şafaktan hemen öncedir.", en: "The darkest hour of the night is just before dawn." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 54, text: { tr: "Huzurlu bir kalple uyumak, en büyük zenginliktir.", en: "Sleeping with a peaceful heart is the greatest wealth." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 55, text: { tr: "Ay, gecenin lambası; yıldızlar, süsüdür.", en: "The moon is the lamp of the night; stars are its ornaments." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 56, text: { tr: "Bazen en iyi plan, hiçbir şey yapmamaktır.", en: "Sometimes the best plan is to do nothing at all." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 57, text: { tr: "Gece, düşlerin başladığı yerdir.", en: "Night is where the dreams begin." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 58, text: { tr: "Sakinlik, fırtınadan sonraki en güzel sestir.", en: "Calmness is the most beautiful sound after a storm." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 59, text: { tr: "Bugünü bırak, yarını uyandığında düşün.", en: "Leave today behind, think about tomorrow when you wake." }, author: { tr: "Anonim", en: "Anonymous" } },
    { id: 60, text: { tr: "En güzel yolculuk, rüyalarda yapılandır.", en: "The most beautiful journey is the one taken in dreams." }, author: { tr: "Anonim", en: "Anonymous" } },
];
